name: Run Tests

on: [push]

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v2

      - name: Install Python
        run: brew install python@3.7 python@3.8 python@3.9

      - name: Install minisign
        run: brew install minisign

      - name: Install python dependencies
        run: pip install -r requirements.txt

      - name: Run Tests
        run: tox
