name: Run Tests

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Python
        run: brew install python@3.9

      - name: Install minisign
        run: brew install minisign

      - name: Install python dependencies
        run: pip install -r requirements.txt

      - name: Run Tests
        run: tox
